# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bb741de71b299e5af848d54e6864fcdfbb2278558092109b792529dd0fd5eb9ffe5982b5e2eb67800e26a20929cfefe2266f4fe9c78bc8670fe3eaedcd78dc7

test:
  secret_key_base: 249c95f2d8c6784e7c96528acdc922fa60f14a1243d9f6b3c432112885d0bc7a91c505338af236492edb207b2ffaf490d5eeb013c184040d20a43fd9305d73b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
